ember-config {
    host = 0.0.0.0
    port = 4041
}

postgres-config {
    n-threads = 32
    url = "jdbc:postgresql:board"
    user = "docker"
    pass = "docker"
}

security-config {
    secret = "secret"
    jwt-expiry-duration = "1 day"
}

email-service-config {
    host = "smtp.ethereal.email",
    port = 587,
    user = "efren.block15@ethereal.email",
    pass = "2s72yw5dAJU6rfXFBk",
    frontend-url = "https://google.com"
}

token-config {
    token-duration = 600000
}

stripe-config {
    price = "price_1RLDWHQ0Kc5bgJKb4UmRFjQt"
    key = ${?STRIPE_API_KEY}
    success-url = "http://localhost:1234/jobs"
    cancel-url = "http://localhost:1234"
    webhook-secret = "whsec_2ef6e3394f81ba96e81f599e569b877b5935094d51e07a927ba7e989585d70b9"
}